bool update_ssid false
string ssid
bool update_passphrase false
string passphrase
bool update_own_ip false
string own_ip
bool update_channel false
uint8 channel
bool update_interface false
string interface
bool update_country_code false
string country_code
---
bool success # indicate successful run of triggered service
string message # informational, e.g. for error messages